language: python

php:
    - '3.7'

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

# command to run tests
script:
  - pylint --load-plugins pylint_flask_sqlalchemy myapp
  - pytest
